/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef SOUNDPOOL_AUTODEFS_H
#define SOUNDPOOL_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_SOUNDPOOL_NAME "soundpool"
#define S3E_EXT_SOUNDPOOL_HASH 0xecd4b8c8

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("soundpool", 9)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !SOUNDPOOL_AUTODEFS_H */
