/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef       void(*sound_pool__init_t)(int maxStreams);
typedef        int(*sound_pool__load_t)(const char* path, int priority);
typedef        int(*sound_pool__play_t)(int soundID, float leftVolume, float rightVolume, int priority, int loop, float rate);
typedef       void(*sound_pool__pause_t)(int streamID);
typedef       void(*sound_pool__resume_t)(int streamID);
typedef       void(*sound_pool__set_looping_t)(int streamID, int loop);
typedef       void(*sound_pool__stop_t)(int streamID);
typedef       void(*sound_pool__unload_t)(int soundID);
typedef       void(*sound_pool__release_t)();

/**
 * struct that gets filled in by soundpoolRegister
 */
typedef struct soundpoolFuncs
{
    sound_pool__init_t m_sound_pool__init;
    sound_pool__load_t m_sound_pool__load;
    sound_pool__play_t m_sound_pool__play;
    sound_pool__pause_t m_sound_pool__pause;
    sound_pool__resume_t m_sound_pool__resume;
    sound_pool__set_looping_t m_sound_pool__set_looping;
    sound_pool__stop_t m_sound_pool__stop;
    sound_pool__unload_t m_sound_pool__unload;
    sound_pool__release_t m_sound_pool__release;
} soundpoolFuncs;
